/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import init.ComboItem;
import init.MainClass;

import javax.swing.JOptionPane;

import utils.HelperClass;
import core.Employee;
import core.Flight;
import exceptions.AddPilotOrFlightAttendantExeption;

/**
 *The class represents the screen which enable users to add {@link core.Pilot } or {@link core.FlightAttendant } to
  {@link core.Flight }
 *
 * @author Matan
 */
public class addPilotOrFlightAttendantToFlight extends MyInternalFrame {

    /**
     * Creates new form addPilotOrFlightAttendantToFlight
     *
     * @param title
     * @param type
     */
    public addPilotOrFlightAttendantToFlight(String title, String type) {
        super(title, type, null);
        initComponents();
        if (title.equals("Add FlightAttendant To Flight")) {
            cbPilots.setVisible(false);
            lblPilot.setVisible(false);
        } else {
            cbFlightAttendant.setVisible(false);
            lblFa.setVisible(false);
        }
        fillFlights();
        btnOk.setToolTipText(utils.Constants.saveButtonToolTip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        cbFlights = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lblFa = new javax.swing.JLabel();
        lblPilot = new javax.swing.JLabel();
        cbPilots = new javax.swing.JComboBox();
        cbFlightAttendant = new javax.swing.JComboBox();
        btnOk = new javax.swing.JButton();

        jLabel1.setText("Select Flight:");

        jLabel3.setText("Source:");

        jLabel4.setText("Destination:");

        cbFlights.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSource, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSource, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFa.setText("Select Flight Attendant:");

        lblPilot.setText("Select Pilot:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFa)
                        .addGap(18, 18, 18)
                        .addComponent(cbFlightAttendant, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPilot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPilots, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPilot)
                    .addComponent(cbPilots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbFlightAttendant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnOk.setText("Submit");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlightsActionPerformed
        // TODO add your handling code here:
        setSelectFlightInfo();
        fillStaff();

    }//GEN-LAST:event_cbFlightsActionPerformed

    /**
     * @param evt
     * @exception {@ link exceptions.AddPilotOrFlightAttendantExeption}
     */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        try {
            if (cbFlights.getModel().getSize() <= 0) {
                shoMissingDataMsg("Flights are missing");
                return;
            }
            if (cbPilots.isVisible() && cbPilots.getModel().getSize() <= 0) {
                shoMissingDataMsg("Pilots are missing");
                return;
            }

            if (cbFlightAttendant.isVisible() && cbFlightAttendant.getModel().getSize() <= 0) {
                shoMissingDataMsg("Flight Attendant are missing");
                return;
            }
            
            int flightNumber = Integer.parseInt(((ComboItem) cbFlights.getSelectedItem()).getValue());
            Flight selectFlight = MainClass.getIfly().getFlights().get(flightNumber);
            int employeeNumber;

            if (cbPilots.isVisible()) {
                employeeNumber = Integer.parseInt(((ComboItem) cbPilots.getSelectedItem()).getValue());
            } else if (cbFlightAttendant.isVisible()) {
                employeeNumber = Integer.parseInt(((ComboItem) cbFlightAttendant.getSelectedItem()).getValue());
            } else {
                return;
            }

            Employee emp = MainClass.getIfly().getEmployees().get(employeeNumber);
            MainClass.getIfly().addPilotOrFlightAttendantToFlight(emp, selectFlight);
            JOptionPane.showInternalConfirmDialog(this, "Saved changes", "Confirmation", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            setIflyState(false);
        } catch (NumberFormatException | AddPilotOrFlightAttendantExeption ex) {
            JOptionPane.showInternalConfirmDialog(this, ex.getMessage(), "Error", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void setSelectFlightInfo() {
        if (cbFlights.getModel().getSize() <= 0) {
            return;
        }

        int flightNumber = Integer.parseInt(((ComboItem) cbFlights.getSelectedItem()).getValue());
        Flight selectFlight = MainClass.getIfly().getFlights().get(flightNumber);
        lblSource.setText(selectFlight.getSource().getCity());
        lblDestination.setText(selectFlight.getDestination().getCity());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cbFlightAttendant;
    private javax.swing.JComboBox cbFlights;
    private javax.swing.JComboBox cbPilots;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFa;
    private javax.swing.JLabel lblPilot;
    private javax.swing.JLabel lblSource;
    // End of variables declaration//GEN-END:variables

    private void fillFlights() {
        HelperClass.fillFlightsCombo(this, cbFlights, cbPilots.isVisible());
        setSelectFlightInfo();
        fillStaff();
    }

    private void fillStaff() {
        int flightNumber = -1;
        if (cbFlights.getModel().getSize() > 0) {
            flightNumber = Integer.parseInt(((ComboItem) cbFlights.getSelectedItem()).getValue());
        }

        Flight selectFlight = MainClass.getIfly().getFlights().get(flightNumber);
        if (cbPilots.isVisible()) {
            HelperClass.fillPilotsCombo(this, cbPilots, selectFlight);
        } else if (cbFlightAttendant.isVisible()) {
            HelperClass.fillFlightAttendantCombo(this, cbFlightAttendant, selectFlight);
        }

    }

}
