/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import utils.QueryCombobox;
import init.ComboItem;
import static init.MainClass.con;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Blob;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import utils.Column;
import static utils.Constants.ADD_MODE;
import static utils.Constants.EDIT_MODE;
import static utils.Constants.OYSTER;
import static utils.Constants.PAPER;
import utils.CustomTableModel;

/**
 *
 * @author asus
 */
public class Card extends MyInternalFrame {

    private int cardNumber;
    private Date purchaseDate;
    private boolean type;
    private ImageIcon picture;
    private JFileChooser picFileChooser;
    private boolean isTourist;

    /**
     * Creates new form Card
     *
     * @param title
     * @param type
     * @param cardNumber
     * @param purchaseDate
     */
    public Card(String title, String type, int cardNumber, Date purchaseDate) {
        super(title, type);
        setMode(EDIT_MODE);
        this.cardNumber = cardNumber;
        this.purchaseDate = purchaseDate;
        setVariables();
        buildForm();
        setDefaults();
    }

    public Card(String title, String type) {
        super(title, type);
        setMode(ADD_MODE);
        this.purchaseDate = null;
        buildForm();

    }

    private void buildForm() {
        initComponents();
        try {
            PreparedStatement getAllCards = con.prepareStatement("SELECT number FROM tblCard");
            PreparedStatement getPurchaseDate = con.prepareStatement("SELECT purchaseDate FROM tblCard "
                    + "WHERE number = ?");
            PreparedStatement getAllCardLengths = con.prepareStatement("SELECT * FROM tblCardLengths");
            PreparedStatement getAllZones = con.prepareStatement("SELECT * FROM tblZone");

            if (getMode() == EDIT_MODE) {
                cmbCard.setModel(new QueryCombobox(cmbCard, Integer.class, getAllCards));
                cmbPurchaseDate.setModel(new QueryCombobox(cmbPurchaseDate, cmbCard, Date.class, getPurchaseDate));
            } else {
                // add mode
                setNewCard();
                cmbCard.setModel(new javax.swing.DefaultComboBoxModel(new ComboItem[]{
                    new ComboItem(cardNumber, String.valueOf(cardNumber))}));
                cmbPurchaseDate.setModel(new javax.swing.DefaultComboBoxModel(new ComboItem[]{
                    new ComboItem(purchaseDate.toString(), purchaseDate.toString())}));
            }

            cmbLength.setModel(new QueryCombobox(cmbLength, Integer.class, getAllCardLengths));
            cmbZone.setModel(new QueryCombobox(cmbZone, Integer.class, getAllZones));

//            setTableProperties(tblPrograms);
            picFileChooser = new JFileChooser();
            setActiveness();
            //pPrograms.setVisible(false);
        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDetails = new javax.swing.JPanel();
        lblCardNumber = new javax.swing.JLabel();
        cmbCard = new javax.swing.JComboBox();
        lblPurchaseDate = new javax.swing.JLabel();
        cmbPurchaseDate = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        chbIsTourist = new javax.swing.JCheckBox();
        btnBrowse = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pPrograms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrograms = new javax.swing.JTable();
        lblZone = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        cmbZone = new javax.swing.JComboBox();
        cmbLength = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        pDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        lblCardNumber.setText("Card Number");

        cmbCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCardActionPerformed(evt);
            }
        });

        lblPurchaseDate.setText("Purchase Date");

        cmbPurchaseDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPurchaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPurchaseDateActionPerformed(evt);
            }
        });

        lblType.setText("Type");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paper", "Oyster" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        chbIsTourist.setText("Tourist");
        chbIsTourist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbIsTouristActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse Image");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDetailsLayout = new javax.swing.GroupLayout(pDetails);
        pDetails.setLayout(pDetailsLayout);
        pDetailsLayout.setHorizontalGroup(
            pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailsLayout.createSequentialGroup()
                        .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDetailsLayout.createSequentialGroup()
                                .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCardNumber)
                                    .addComponent(lblPurchaseDate)
                                    .addComponent(lblType))
                                .addGap(18, 18, 18)
                                .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCard, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(chbIsTourist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pDetailsLayout.setVerticalGroup(
            pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsLayout.createSequentialGroup()
                .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailsLayout.createSequentialGroup()
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrowse))
                    .addGroup(pDetailsLayout.createSequentialGroup()
                        .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCardNumber)
                            .addComponent(cmbCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPurchaseDate)
                            .addComponent(cmbPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType))
                        .addGap(18, 18, 18)
                        .addComponent(chbIsTourist)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pPrograms.setBorder(javax.swing.BorderFactory.createTitledBorder("Programs"));

        tblPrograms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrograms);

        lblZone.setText("Zone");

        lblLength.setText("Length");

        cmbZone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbLength.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProgramsLayout = new javax.swing.GroupLayout(pPrograms);
        pPrograms.setLayout(pProgramsLayout);
        pProgramsLayout.setHorizontalGroup(
            pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgramsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pProgramsLayout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd))
                    .addGroup(pProgramsLayout.createSequentialGroup()
                        .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLength)
                            .addComponent(lblZone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLength, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbZone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pProgramsLayout.setVerticalGroup(
            pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgramsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pProgramsLayout.createSequentialGroup()
                        .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLength))
                        .addGap(38, 38, 38)
                        .addGroup(pProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnRemove)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCardActionPerformed
        try {
            ComboItem cardItem = (ComboItem) cmbCard.getSelectedItem();
            this.cardNumber = Integer.parseInt(cardItem.getKey().toString());
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_cmbCardActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        String strType = (String) cmbType.getSelectedItem();
        this.type = (strType.equals("Oyster")) ? OYSTER : PAPER;
        modifyFormToCardType();
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        int o = picFileChooser.showOpenDialog(this);
        if (o == JFileChooser.APPROVE_OPTION) {
            try {
                File f = picFileChooser.getSelectedFile();
                Path p = f.toPath();
                byte[] b =  Files.readAllBytes(p);
                ImageIcon icon = getScaledImage(b);
                lblPicture.setIcon(icon);
                this.picture = icon;
            } catch (IOException ex) {
                Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String tableName = (this.type == PAPER) ? "tblPaperCardAreas" : "tblOysterCardAreas";
        ComboItem zoneItem;
        ComboItem lengthItem;
        int zone;
        double length;

        PreparedStatement st;
        try {
            zoneItem = (ComboItem) cmbZone.getSelectedItem();
            lengthItem = (ComboItem) cmbLength.getSelectedItem();
            zone = Integer.parseInt(zoneItem.getKey().toString());
            length = Double.valueOf(lengthItem.getKey().toString());

            st = con.prepareStatement("INSERT INTO " + tableName + " VALUES (?,?,?,?)");
            st.setInt(1, this.cardNumber);
            st.setDate(2, this.purchaseDate);
            st.setInt(3, zone);
            st.setDouble(4, length);
//            st.executeUpdate();

            ((CustomTableModel) tblPrograms.getModel()).addRow(new Object[]{zone, length});

        } catch (SQLException | NullPointerException ex) {
//            Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbPurchaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPurchaseDateActionPerformed
        ComboItem purchaseDateItem = (ComboItem) cmbPurchaseDate.getSelectedItem();
        this.purchaseDate = (Date) purchaseDateItem.getKey();
    }//GEN-LAST:event_cmbPurchaseDateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String tableName = (this.type == PAPER) ? "tblPaperCardAreas" : "tblOysterCardAreas";
        ComboItem zoneItem;
        ComboItem lengthItem;
        int zone;
        double length;

        PreparedStatement st;
        try {
            zoneItem = (ComboItem) cmbZone.getSelectedItem();
            lengthItem = (ComboItem) cmbLength.getSelectedItem();
            zone = Integer.parseInt(zoneItem.getKey().toString());
            length = Double.valueOf(lengthItem.getKey().toString());

            st = con.prepareStatement("DELETE FROM " + tableName + " WHERE cardNumber = ? "
                    + "and cardPurchaseDate = ? and zoneNumber = ? and cardLength = ?");
            st.setInt(1, this.cardNumber);
            st.setDate(2, this.purchaseDate);
            st.setInt(3, zone);
            st.setDouble(4, length);
            st.executeUpdate();

            ((CustomTableModel) tblPrograms.getModel()).removeRow(tblPrograms.getSelectedRow());

        } catch (SQLException | NullPointerException ex) {
//            Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void chbIsTouristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbIsTouristActionPerformed
        this.isTourist = chbIsTourist.isSelected();
    }//GEN-LAST:event_chbIsTouristActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
//        cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //pPrograms.setVisible(true);
//        saveFields();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chbIsTourist;
    private javax.swing.JComboBox cmbCard;
    private javax.swing.JComboBox cmbLength;
    private javax.swing.JComboBox cmbPurchaseDate;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JComboBox cmbZone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPurchaseDate;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblZone;
    private javax.swing.JPanel pDetails;
    private javax.swing.JPanel pPrograms;
    private javax.swing.JTable tblPrograms;
    // End of variables declaration//GEN-END:variables

    private void fillPrograms() {
        PreparedStatement st;
        ResultSet rs;

        ArrayList<Column> cols = new ArrayList<>();
        cols.add(new Column("#", "#", Integer.class)); //*UNBOUND to DB - displays row num*/
        cols.add(new Column("Zone", "zoneNumber", Integer.class));
        cols.add(new Column("Length", "cardLength", Double.class));

        try {
            String tableName = this.type == PAPER ? "tblPaperCardAreas" : "tblOysterCardAreas";
            PreparedStatement getAllPrograms = con.prepareStatement("SELECT * FROM " + tableName + " As CA "
                    + "JOIN tblCardLengths As CL on CA.cardLength = CL.lengthDescription "
                    + "WHERE CA.cardNumber = ? and CA.cardPurchaseDate = ?");
            getAllPrograms.setInt(1, this.cardNumber);
            getAllPrograms.setDate(2, this.purchaseDate);

            CustomTableModel programTableModel = new CustomTableModel(tblPrograms, cols, null/*no add statement*/, getAllPrograms);
            tblPrograms.setModel(programTableModel);
        } catch (SQLException ex) {

        }
    }
//        try {
//            String tableName = this.type == PAPER ? "tblPaperCardAreas" : "tblOysterCardAreas";
//            st = con.prepareStatement("SELECT * FROM " + tableName + " As CA "
//                    + "JOIN tblCardLengths As CL on CA.cardLength = CL.lengthDescription "
//                    + "WHERE CA.cardNumber = ? and CA.cardPurchaseDate = ?");
//            st.setInt(1, this.cardNumber);
//            st.setDate(2, this.purchaseDate);
//            rs = st.executeQuery();
//            ArrayList<Object[]> rows = new ArrayList();
//            
//            int i = 0;
//            while (rs.next()) {
//                Object[] row = {i, rs.getInt("zoneNumber"), rs.getString("lengthDescription")};
//                rows.add(row);
//                i++;
//            }
//            MyTableModel tableModel = new MyTableModel(programColumns, rows, null);
//            tblPrograms.setModel(tableModel);
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Card.class
//                    .getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    private void setDefaults() {
//        int defaultCard = Integer.valueOf(((ComboItem) cmbCard.getSelectedItem())
//                .getKey().toString());
//        ((QueryCombobox)cmbPurchaseDate.getModel()).fill(defaultCard);
//        ((QueryCombobox)cmbCard.getModel()).fill(cardNumber);

        cmbCard.getModel().setSelectedItem(this.cardNumber);
        cmbPurchaseDate.setSelectedItem(String.valueOf(this.purchaseDate));

        cmbType.setSelectedItem((this.type == PAPER) ? "Paper" : "Oyster");
        // TODO: get picture from DB

        if (this.type == OYSTER) {
            lblPicture.setIcon(this.picture); //TODO: CHECK THIS
        } else {
            // paper
            chbIsTourist.setSelected(this.isTourist);
        }
    }

    private Image scaleIamge(Image img, int w, int h) {

        BufferedImage resizeImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizeImage.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);
        g.drawImage(img, 0, 0, w, h, null);
        g.dispose();
        return resizeImage;

    }

    private ImageIcon getScaledImage(byte[] blobAsBytes) {
        try {
            BufferedImage bufferedImage = ImageIO.read(new ByteArrayInputStream(blobAsBytes));
            if (bufferedImage != null) {
                ImageIcon resized = new ImageIcon(scaleIamge(bufferedImage, 120, 110));

                return resized;
            }
            return null;
        } catch (IOException ex) {
            Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    private void setVariables() {
        PreparedStatement st;
        ResultSet rs;
        try {
            st = con.prepareStatement("SELECT * FROM tblOysterCard WHERE "
                    + "number = ? and purchaseDate = ?");
            st.setInt(1, cardNumber);
            st.setString(2, this.purchaseDate.toString());

            rs = st.executeQuery();

            if (rs.isBeforeFirst()) {
                // result set not empty - the card is Oyster
                this.type = OYSTER;
                rs.next();

                //this.picture = rs.getObject("picture", ImageIcon.class); //TODO: FIX THIS IMPORT
                Blob blob = rs.getBlob("picture");
                int blobLength = (int) blob.length();
                byte[] blobAsBytes = blob.getBytes(1, blobLength);
                this.picture = getScaledImage(blobAsBytes);

            } else {
                // result set is empty - the card is Paper
                st = con.prepareStatement("SELECT isTourist FROM tblPaperCard WHERE "
                        + "number = ? and purchaseDate = ?");
                st.setInt(1, cardNumber);
                st.setString(2, this.purchaseDate.toString());

                rs = st.executeQuery();

                this.type = PAPER;
                rs.next();
                this.isTourist = rs.getBoolean("isTourist"); // //TODO: CHECK IF CORRECT
            }

        } catch (SQLException ex) {
            System.out.println("ex = " + ex.getMessage());
            Logger.getLogger(Card.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setActiveness() {
        cmbCard.setEnabled(false);
        cmbPurchaseDate.setEnabled(false);

        if (getMode() == ADD_MODE) {
            cmbType.setEnabled(true);

        } else {
            // edit mode

            cmbType.setEnabled(false);

        }
        modifyFormToCardType();
    }

    private void modifyFormToCardType() {
        if (this.type == OYSTER) {
            lblPicture.setVisible(true);
            btnBrowse.setVisible(true);
            chbIsTourist.setVisible(false);
        } else {
            // paper
            lblPicture.setVisible(false);
            btnBrowse.setVisible(false);
            chbIsTourist.setVisible(true);
        }
        fillPrograms();
    }

    private void setNewCard() {
        Statement st;
        ResultSet rs;

        try {
            st = con.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("SELECT number FROM tblCard");

            rs.last();
            this.cardNumber = rs.getInt("number") + 1;
            this.purchaseDate = new Date(new java.util.Date().getTime());

        } catch (SQLException ex) {
            Logger.getLogger(Station.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
