/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static init.MainClass.con;
import init.MyTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static utils.Constants.EDIT_MODE;
import utils.HelperClass;
import utils.Queries;

/**
 *
 * @author asus
 */
public class Deposits extends MyInternalFrame {

    private int fromYear;
    private int toYear;
    private double price;
    private final String[] DepositColumns = new String[]{"Start Year", "End Year", "Price"};

    /**
     * Creates new form GeneralParameters
     *
     * @param title
     * @param type
     */
    public Deposits(String title, String type) {
        super(title, type);
        setMode(EDIT_MODE);
        initComponents();
        fillDeposits();

        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(Queries.NEXT_DEPOSIT_YEAR);
            rs.next();
            int nextDepositYear = rs.getInt("next year");
            ychFrom.setStartYear(nextDepositYear);
            ychTo.setStartYear(nextDepositYear + 1);

            ychFrom.setYear(nextDepositYear);
            ychTo.setYear(nextDepositYear + 1);
            ychFrom.setEnabled(false);
        } catch (SQLException e) {
            System.err.println("Error code: " + e.getErrorCode() + "\nError Message: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ychTo = new com.toedter.calendar.JYearChooser();
        tfDeposit = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblIs = new javax.swing.JLabel();
        lblDepositFees = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeposits = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        ychFrom = new com.toedter.calendar.JYearChooser();

        ychTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ychToPropertyChange(evt);
            }
        });

        tfDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDepositActionPerformed(evt);
            }
        });

        lblFrom.setText("Deposit from");

        lblTo.setText("to");

        lblIs.setText("is");

        lblDepositFees.setText("Deposit Fees");

        tblDeposits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDeposits);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSubmit.setText("Save");

        btnCancel.setText("Cancel");

        btnCreate.setText("Add");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(tfDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFrom)
                                                .addGap(18, 18, 18)
                                                .addComponent(ychFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(lblTo))
                                            .addComponent(lblDepositFees))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ychTo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblIs)))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTo)
                    .addComponent(lblFrom)
                    .addComponent(ychTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIs)
                        .addComponent(tfDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreate)
                    .addComponent(ychFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblDepositFees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSubmit))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        PreparedStatement st;

        try {

            fromYear = ychFrom.getYear();
            toYear = ychTo.getYear();

            st = con.prepareStatement("DELETE FROM tblGeneralParameters WHERE "
                    + "depositStartYear = ? and depositEndYear = ?");
            st.setInt(1, fromYear);
            st.setInt(2, toYear);
            st.executeUpdate();

            fillDeposits();
        } catch (SQLException ex) {
            Logger.getLogger(Station.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        PreparedStatement st;

        try {

            fromYear = ychFrom.getYear();
            toYear = ychTo.getYear();
            this.price = Double.parseDouble(tfDeposit.getText());

            st = con.prepareStatement("INSERT INTO tblGeneralParameters VALUES (?,?,?)");
            st.setInt(1, fromYear);
            st.setInt(2, toYear);
            st.setDouble(3, this.price);
            st.executeUpdate();
            fillDeposits();

        } catch (SQLException | NullPointerException ex) {
//            Logger.getLogger(Station.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void ychToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ychToPropertyChange
        this.toYear = ychTo.getYear();
    }//GEN-LAST:event_ychToPropertyChange

    private void tfDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDepositActionPerformed
        this.price = Double.valueOf(tfDeposit.getText());
    }//GEN-LAST:event_tfDepositActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepositFees;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblIs;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tblDeposits;
    private javax.swing.JTextField tfDeposit;
    private com.toedter.calendar.JYearChooser ychFrom;
    private com.toedter.calendar.JYearChooser ychTo;
    // End of variables declaration//GEN-END:variables

    private void fillFields() {
        PreparedStatement st;
        ResultSet rs;
        try {
            st = con.prepareStatement("Select * From tblGeneralParameters As GP "
                    + "WHERE GP.depositStartYear = ? and GP.depositEndYear = ?");
            st.setInt(1, this.fromYear);
            st.setInt(2, this.toYear);
            rs = st.executeQuery();

            rs.next();
            ychFrom.setYear(rs.getInt("depositStartYear"));
            ychTo.setYear(rs.getInt("depositEndYear"));
            tfDeposit.setText(rs.getString("price"));
        } catch (SQLException ex) {
            Logger.getLogger(Deposits.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillDeposits() {
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(Queries.SELECT_ALL_DEPOSITS);
            tblDeposits.setModel(HelperClass.buildTableModel(rs));
        } catch (SQLException e){
            
        }
    }
}
