/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import init.ComboItem;
import static init.MainClass.con;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utils.QueryCombobox;

/**
 *
 * @author Matan
 */
public class SiteDialog extends MyInternalFrame {

    MainWindow mainWindow;
    short siteID;

    /**
     * Creates new form SiteDialog
     */
    public SiteDialog(String title, String type, MainWindow parent) {
        super(title, type);
        initComponents();
        this.mainWindow = parent;
        fillCmbSite();
        setVariables();
    }

    private void setVariables() {
        ComboItem item = (ComboItem) cmbSide.getSelectedItem();
        if (item == null) {
            return;
        }
        this.siteID = ((Short)item.getKey());
    }

    private void fillCmbSite() {
        PreparedStatement st;
        try {
            st = con.prepareStatement("SELECT ID,name FROM tblSite");

            cmbSide.setModel(new QueryCombobox(cmbSide, Short.class, st));

        } catch (SQLException ex) {
            JOptionPane.showInternalMessageDialog(this,
                    "There was an error retrieving data",
                    "Bummer!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSide = new javax.swing.JComboBox();
        btnCancel = new javax.swing.JButton();
        bntOK = new javax.swing.JButton();
        lblSiteName = new javax.swing.JLabel();

        cmbSide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSideActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        bntOK.setText("OK");
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        lblSiteName.setText("Site Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSiteName)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(cmbSide, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSiteName)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cmbSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntOK)
                        .addComponent(btnCancel))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSideActionPerformed

        ComboItem item = (ComboItem) cmbSide.getSelectedItem();
        this.siteID = ((Short) item.getKey());
    }//GEN-LAST:event_cmbSideActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        mainWindow.getDesktop().remove(this);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
        // TODO add your handling code here:
        if (this.siteID > 0) {

            this.setVisible(false);
            mainWindow.getDesktop().remove(this);
            Site s = new Site(title, getSelectedUserType(), this.siteID);
            mainWindow.createFrame(s);
        }
    }//GEN-LAST:event_bntOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntOK;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cmbSide;
    private javax.swing.JLabel lblSiteName;
    // End of variables declaration//GEN-END:variables
}
